#!/bin/sh

#
# Installation script
#
# 1) cp ikmc.config.default ikmc.config
# 2) Install 
#

Usage=Install

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

#
#  Verify the arguments to the script, there shouldn't be any
#
if [ $# -ne 0 ]
then
    echo "Usage: ${Usage}"
    installFailed
fi

#
# Make sure config files exist
#
cd `dirname $0`

# establish the config files
MAIN_CONFIG=ikmc.config

# Make sure config file exists and source it
if [ -r ${MAIN_CONFIG} ]
then
    echo "Source ${MAIN_CONFIG}"
    . ${MAIN_CONFIG}
else
    echo "Cannot source configuration file: ${MAIN_CONFIG}"
    installFailed
fi

# Create a copy of the default index page that has the proper FTPURL
# substituted in it and copy it to the FTP report directory.
#
rm -f ikmc_index.html
sed "s/INCLUDE_FTPURL/$FTPURL/" ikmc_index.html.default > ikmc_index.html

# Check to see if this is a development installation
#
DEV=""
if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi

#
# run DLAInstall for each configuration file
#
for c in ${ALLELELOAD}/*.config
do
echo 'running DLAINSTALL' ${c}
. ${c}
${DLAINSTALL} ${DEV}
mkdir -p ${INPUTDIR}
done

